#!/bin/bash
java -jar --module-path /home/christoph/Development_Projects/PostModernChess/javafx.base.jar:/home/christoph/Development_Projects/PostModernChess/javafx.graphics.jar:/home/christoph/Development_Projects/PostModernChess/javafx.controls.jar:/home/christoph/Development_Projects/PostModernChess/javafx.fxml.jar --add-modules javafx.base,javafx.graphics,javafx.controls,javafx.fxml /home/christoph/Development_Projects/PostModernChess/Postmodern_Chess.jar

